services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Api\Behat\:
        resource: '../src/Behat/*'

    Behatch\Context\BrowserContext:
        class: Behatch\Context\BrowserContext
