doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '13.9'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            datetime_immutable: \Carbon\Doctrine\DateTimeImmutableType
            datetime: \Carbon\Doctrine\DateTimeType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            app:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/vendor/appname/app-core/src/Domain'
                prefix: 'App\Domain'
                alias: app
