framework:
    messenger:
        default_bus: command.bus
        buses:
            event.bus: ~
            command.bus:
                middleware:
                    - dispatch_after_current_bus
                    - doctrine_transaction
